dev: restore transmission

diff --git a/204-k3s-prod/manifests/transmission.yaml b/204-k3s-prod/manifests/transmission.yaml
--- a/204-k3s-prod/manifests/transmission.yaml
+++ b/204-k3s-prod/manifests/transmission.yaml
@@ -20,11 +20,8 @@ spec:
       labels:
         app: transmission
     spec:
-      dnsConfig:
-        options:
-          - name: ndots
-            value: "1"
       volumes:
+        # Required for Wireguard tunnel device in many setups
         - name: tun
           hostPath:
             path: /dev/net/tun
@@ -49,35 +46,42 @@ spec:
               value: "protonvpn"
             - name: VPN_TYPE
               value: "wireguard"
-            - name: DNS_UPSTREAM_RESOLVER_TYPE
-              value: "plain"
             - name: WIREGUARD_PRIVATE_KEY
               valueFrom:
                 secretKeyRef:
                   name: gluetun-secret
                   key: WIREGUARD_PRIVATE_KEY
+
+            - name: UPDATER_PERIOD
+              value: "24h"
+            - name: PORT_FORWARD_ONLY
+              value: "on"
+            - name: VPN_PORT_FORWARDING
+              value: "on"
+            - name: DNS_ADDRESS
+              value: "1.1.1.1"
           ports:
             - name: http-proxy
               containerPort: 8888
               protocol: TCP
         - name: ping
-          image: curlimages/curl:8.18.0
+          image: busybox:1.37.0
           command:
             - sh
             - -c
             - |
-              while ! curl -m 1 -s 4.ident.me; do
-                echo "Probe failed, retrying"
-                sleep 1
+              while ! ping -c 1 1.1.1.1; do
+                echo "Ping failed, retrying in 5"
+                sleep 5
               done
-              echo "probe succesfull, exiting"
+              echo "ping succesfull, exiting"
       containers:
         - name: curlpod
           image: curlimages/curl:8.18.0
           args:
             - /bin/sh
             - -c
-            - while true; do curl -m 1 -s 4.ident.me; echo; sleep 5; done
+            - while true; do curl -s 4.ident.me; echo; sleep 15; done
           imagePullPolicy: Always
 
         - name: transmission
@@ -109,11 +113,6 @@ spec:
               port: 9091
             initialDelaySeconds: 5
             periodSeconds: 10
-          startupProbe:
-            tcpSocket:
-              port: 9091
-            failureThreshold: 30
-            periodSeconds: 5
 ---
 apiVersion: v1
 kind: PersistentVolumeClaim
